[toolchain]

[features]
seeds = true
skip-lint = false

[programs.devnet]
bonding_curve = "7Ygc43fvZUGNujq1uzvww9b2kY71UMAptiv6vvYWK91S"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keys/users.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradeable = false
